### ISSUE TITLE
Unable to find market listing item image

### ISSUE THREAD

**Issue by RyleyGG** [fabieu/steam-market-history#15]
**Bug:** After signing in with steam-market-history CLI, command fails to find listing item image and errors out.

**Steps to replicate:**
1. Run the following command: steam-market-history export --csv --path <path>
2. Login to CLI
3. Error will occur after a few seconds

**Traceback:**
`
  File "<path>\steam_market_history\modules\steam.py", line 63, in fetch_market_history
    market_listing_item_img = row.find("img", class_="market_listing_item_img")["src"]
TypeError: 'NoneType' object is not subscriptable`

**Comment by fabieu** [comment]
Hey @RyleyGG, 
I was able to recreate the error and fixed it immediately. It seems there was an change in the Steam API, which causes empty image src tags. The new behaviour is that images will be ignored if not present.
Thanks for contributing and have a nice day!

**Comment by fabieu** [comment]
steam-market-history 3.0.4 is now available: https://pypi.org/project/steam-market-history/
